version: '3'
services:
  short-link:
    container_name: solventum-short-link
    image: openjdk:17-jdk-alpine
    ports:
      - 8080:8080
    volumes:
      - .:/app
    working_dir: /app
    command: ["./mvnw", "spring-boot:run"]